increased activeOpacity and updated default to primary
GeekyAnts/NativeBase pull request #3560
Opened 2021-03-22 08:30 UTC by MD-REHMAN

2021-03-22 10:15 UTC, Ajamuar requested changes

2021-03-22 10:15 UTC, Ajamuar commented on src/components/primitives/Checkbox/types.tsx
> +  colorScheme?: string | 'primary.';
`primary.`?

2021-03-22 10:15 UTC, Ajamuar commented on example/storybook/stories/components/primitives/Radio/playground.tsx
> +          colorScheme={text('colorScheme', 'primary.')}
`primary.`

2021-03-22 10:15 UTC, Ajamuar commented on src/components/primitives/Radio/types.tsx
> +  colorScheme?: string | 'primary.';
`primary.`?

2021-03-23 10:59 UTC, MD-REHMAN commented
No longer required.

2021-03-23 10:59 UTC, closed without merging